spring:
  application:
    name: config-server
#  security:
#    user:
#      name: 123456
#      password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/test/config-server.git
          #username: 123
          #password: 123
          #basedir:
      label: master

server:
  port: 8761

  eureka.client.healthcheck.enabled=true
  # 续约更新时间间隔（默认30秒）
  eureka.instance.lease-renewal-interval-in-seconds=10
  # 续约到期时间（默认90秒）
  eureka.instance.lease-expiration-duration-in-seconds=10

  #连接GitHub
  spring.cloud.config.server.git.uri=https://github.com/huanzi-qch/config-server.git
  spring.cloud.config.server.git.search-paths=config-server
  spring.cloud.config.label=master
  spring.cloud.config.server.git.username=******
  spring.cloud.config.server.git.password=******

eureka:
  client:
    #健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    #表示是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个
    service-url:
      #defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
    #每30秒捕获一次
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    #status显示
    instance-id: 127.0.0.1




logging:
  level:
    com.sunny: debug

